Change test to reproduce the same bug in h2 also
Previously the test was causing
org.squeryl.h2.H2_KickTheTires to fail with
org.squeryl.SquerylSQLException: Exception while executing statement : Unknown data type: "V2"; SQL statement: